### ISSUE TITLE
create upcoming event card

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [ax-studios/frontend-web#12]

**Comment by Chandraprakash-Darji** [comment]
Design for Upcoming Event card
![image](https://user-images.githubusercontent.com/93640141/194728409-6f972761-be22-407f-952a-daa2e17cc53b.png)

For data, you can create in `src/data/upcoming-event` and then add it at the user context

The wrapper component is in `/src/components/pages/dashbaord/Home/index.js`

you can create a different folder for the wrapper.

**Comment by Anjali2201** [comment]
Would like to work on this

**Comment by Chandraprakash-Darji** [comment]
Sure I assign you the issue
