### ISSUE TITLE
create today's class schedule

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [ax-studios/frontend-web#15]

**Comment by Chandraprakash-Darji** [comment]
Design for today's schedule 
![image](https://user-images.githubusercontent.com/93640141/194728256-819be53a-8295-4c61-9c01-42fb978cf52a.png)

For data you can create in `src/data/today-schedule` and then add to user context

**Comment by arinchaik** [comment]
can you assigned to me

**Comment by Chandraprakash-Darji** [comment]
Sure work on it

**Comment by arinchaik** [comment]
`Permission to ax-studios/frontend-web.git denied to me` can u help

**Comment by arinchaik** [comment]
when i try to pushing new branch

**Comment by Chandraprakash-Darji** [comment]
Have you fork it.?

**Comment by Chandraprakash-Darji** [comment]
Good Work brother keep it up
