### ISSUE TITLE
Create News for AI Card

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [ax-studios/frontend-web#17]
Design for NEWS card
![image](https://user-images.githubusercontent.com/93640141/194728409-6f972761-be22-407f-952a-daa2e17cc53b.png)

For data, you can create in `src/data/news `and then add it at the user context

The wrapper component is in `/src/components/pages/dashbaord/Home/index.js`

you can create a different folder for the wrapper.

**Comment by logicalahara** [comment]
@Chandraprakash-Darji I've got a grip over the tech involved and would love to contribute to this ticket

### please assign this ticket to me

**Comment by Chandraprakash-Darji** [comment]
Sure

**Comment by logicalahara** [comment]
after looking into the design, I can see `News of AI` section at the right, do we need to design only this ? correct me if wrong

**Comment by Chandraprakash-Darji** [comment]
You need to code News for AI section

**Comment by Chandraprakash-Darji** [comment]
@logicalahara  Need any help while creating this

**Comment by logicalahara** [comment]
@Chandraprakash-Darji Please review - https://github.com/ax-studios/frontend-web/pull/40
