### ISSUE TITLE
Replace profile toggle with sliding toggle block

### ISSUE THREAD

**Issue by VasuDevrani** [ax-studios/frontend-web#48]
**Is your feature request related to a problem? Please describe.**
The toggle option on the Profile page doesn't look good. 

**Describe the solution you'd like**
We can replace it with a block that slides left or right whenever it is toggled

**Additional context**
<img width="467" alt="image" src="https://user-images.githubusercontent.com/101383635/198205685-09573d18-6054-4fca-bda5-0e674ac489dc.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/101383635/198205628-d87115f9-f5a8-4fc6-a030-7f9ff3294726.png">

**Comment by VasuDevrani** [comment]
But, I can't figure out where have you built these classes like ```no-animation``` or ```text-base-content``` etc
<img width="340" alt="image" src="https://user-images.githubusercontent.com/101383635/198209346-e4e38fd5-2aa8-4ad5-b998-20cf4e967011.png">

**Comment by Chandraprakash-Darji** [comment]
This are coming from daisyUI library

**Comment by Chandraprakash-Darji** [comment]
Have created this changes If you have any suggestion say

**Comment by VasuDevrani** [comment]
Ya... it looks great.

**Comment by Chandraprakash-Darji** [comment]
Thanks for figuring out
